name: CycloneDX

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
  
jobs:
  ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.7
      - name: CycloneDX Python Generate SBOM
        uses: CycloneDX/gh-python-generate-sbom@v1.0.0
    
  ubuntu-eighteen:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: CycloneDX Python Generate SBOM
        uses: CycloneDX/gh-python-generate-sbom@v1.0.0
    
  
  ubuntu-sixteen:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - name: CycloneDX Python Generate SBOM
        uses: CycloneDX/gh-python-generate-sbom@v1.0.0
        
  
  windows-latest:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: CycloneDX Python Generate SBOM
        uses: CycloneDX/gh-python-generate-sbom@v1.0.0
        
  
  windows-nineteen:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: CycloneDX Python Generate SBOM
        uses: CycloneDX/gh-python-generate-sbom@v1.0.0
    
  macos-latest:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: CycloneDX Python Generate SBOM
        uses: CycloneDX/gh-python-generate-sbom@v1.0.0
    
  macos-fifteen:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: CycloneDX Python Generate SBOM
        uses: CycloneDX/gh-python-generate-sbom@v1.0.0
